### ISSUE TITLE
Request - The slides that you used in your talk

### ISSUE THREAD

**Issue by Ram-N** [mdagost/pugme-jupyter#3]
@mdagost,

I found this repo through your YT talk https://www.youtube.com/watch?v=Z4swQ-lUo7Y&t=343s
Could you perhaps make the slides available here on github or some other share site?

Thanks much.

**Comment by mdagost** [comment]
@Ram-N Sorry--I took a look but for some reason can't find the slides anywhere.  They're likely on an old work laptop :(
